name: 'snowflake_dbt'
version: '1.0'

profile: 'snowflake_dbt'

model-paths: ["models"]

models:
  snowflake_dbt:
    +materialized: table 
    
    raw:
      +schema: RAW

    stg:
      +schema: STG

    dwh:
      +schema: DWH
