name: 'snowflake_dbt'
version: '1.0'

profile: 'snowflake_dbt'

model-paths: ["models"]
macro-paths: ["macros"]

models:
  snowflake_dbt:
    +materialized: table
    +schema: "{{ generate_schema_name(None, this) }}"
    +alias: "{{ generate_alias_name(None, this) }}"
    
    raw:
      +schema: RAW

    stg:
      +schema: STG

    dwh:
      +schema: DWH
